### ISSUE TITLE
Ideas around use of this library in projects

### ISSUE THREAD

**Issue by matatk** [MarkWithall/TESTickle#1]
@tomfinnie and I have started using this for an Arduino project of his: a programmable strip of LED lights.  It is great; thanks!  We were wondering if we could contribute to it in order to make it more readily usable from other projects, more as if it were a library perhaps.  Not exactly sure what modifications would be necessary to achieve this, but here are some thoughts…
1. It would be ideal if we could use a git submodule to include this repo in the client repo, and not have to modify any TESTickle files in order to use it.  I have a feeling that if we were to submodule TESTickle in, we'd not be able to alter any of the files in its directory - that could make the rest of the stuff a bit trickier.
2. Currently the easiest way to make the test harness was to overwrite test.c in the client repo.
3. We also had to add our library under test to the Makefile [which meant modifying this line](https://github.com/tomfinnie/LEDstrip/blob/ruination/switched/tests/Makefile#L31) — would be good to not have to modify your upstream Makefile if possible.  Also I think your (offline) suggestion of having the Makefile automatically pick up files named `*.test.c` and make a test harness and executable binary for them would be a great idea.
4. Note that, because an Arduino 'sketch' automatically includes all C files in the same directory as the main program's code (the `.ino` file) we had to include TESTickle in a separate directory and refer to code in the parent directory.  This actually seems good separation of concerns, so is probably a good thing anyway; just flagging it here.

If you want to give us some direction as to what we should include in a PR, let us know.
- Modifying Makefile to pick up `*.test.c` seems like low-hanging fruit.
- Need to figure out a way to tell TESTickle where our library code is.
- Need to (IMO) make it possible to use git submodules to grab TESTickle.
- Using a higher-level configuration system to generate the Makefile is one possible way to do it (and is a classic approach) but that would involve more cycles than I have ATM, and would risk introducing a lot more in the way of dependencies and portability challenges, perhaps.

Thanks!

**Comment by MarkWithall** [comment]
This should now be possible using TESTickle as a submodule. (see https://github.com/MarkWithall/clistoris as an example)

**Comment by matatk** [comment]
Have been trying with the submodule; looks good so far.  I have a question about how to DRY this up, though... the two stanzas are very similar but I've had a go, and been unsuccessful so far, at making them less repetitive: https://github.com/matatk/LEDstrip/blob/submodule-testickle/switched/tests/Makefile#L18,L22 -- just wondering if you had any thoughts/ideas?  It doesn't seem that you can pass [what I think is] a list such as `%.test.c` to the `test_files_for` function.

**Comment by MarkWithall** [comment]
I think a big part of the problem here is that function calling syntax in Makefiles is very verbose.

**Comment by matatk** [comment]
Maybe this is one reason why sometimes Makefiles are generated with macros.  I can think of two ways around this...
1. Generate the Makefile with macros (which seems way OTT in this small case), or
2. Find some way to template the rule, if that's possible, so that a function can generate the rules for each `.test.c` file in the current directory.

Neither of these are TESTickle issues directly, of course, but I imagine may be of interest to its users.  I will have a go and see what I can concoct...

**Comment by matatk** [comment]
Thanks for the progress on this one; since it was written all of the issues, particularly those relating to TESTickle as a library, have been addressed -- happy to close now :-).
