### ISSUE TITLE
`make test` fails to run the exe but ./sample.test runs

### ISSUE THREAD

**Issue by matatk** [MarkWithall/TESTickle#7]
I'm running 2bf59b1fa1f8b7407caba529309f284097b54104 on Mac OS X 10.11.2.

When I run `make test` I get this output:

```
➜  TESTickle make test
perl test_generator.pl sample.test.c > sample.test.runner.c
gcc -fms-extensions -std=c99 -Wall -Wextra -Werror -g -o sample.test.o -c sample.test.c
gcc -fms-extensions -std=c99 -Wall -Wextra -Werror -g -o sample.test sample.test.runner.c sample.test.o
prove -f -e "" sample.test
Could not execute (sample.test): open3: exec of sample.test failed at /Users/matatk/perl5/perlbrew/perls/perl-5.22.0/lib/5.22.0/TAP/Parser/Iterator/Process.pm line 165.
make: *** [test] Error 2
```

but when I run `make` and then `./sample.test` I get this output (i.e. it works):

```
➜  TESTickle ./sample.test
TAP version 13
1..18
ok 1 - passing_true_test
not ok 2 - failing_true_test
  ---
  message: One should not be the same as itself
  severity: fail
  ...
ok 3 - passing_false_test
not ok 4 - failing_false_test
  ---
  message: One should not be the same as itself
  severity: fail
  ...
ok 5 - passing_equal_test
not ok 6 - failing_equal_test
  ---
  message: One should equal two
  severity: fail
  data:
    got: '1'
    expect: '2'
  ...
ok 7 - passing_not_equal_test
not ok 8 - failing_not_equal_test
  ---
  message: Pi should not be the same as itself
  severity: fail
  ...
ok 9 - passing_string_equal_test
not ok 10 - failing_string_equal_test
  ---
  message: Hello should equal World
  severity: fail
  data:
    got: 'Hello'
    expect: 'World'
  ...
ok 11 - passing_string_empty_test
not ok 12 - failing_string_empty_test
  ---
  message: String should be empty
  severity: fail
  data:
    got: 'Hello'
    expect: ''
  ...
ok 13 - passing_string_not_empty_test
not ok 14 - failing_string_not_empty_test
  ---
  message: String should not be empty
  severity: fail
  ...
ok 15 - passing_null_test
not ok 16 - failing_null_test
  ---
  message: Pointer should be NULL
  severity: fail
  ...
ok 17 - passing_not_null_test
not ok 18 - failing_not_null_test
  ---
  message: Pointer should not be NULL
  severity: fail
  ...
```

I installed Perl as per the README; here's the info...

```
➜  TESTickle perlbrew info
Current perl:
  Name: perl-5.22.0
  Path: /Users/matatk/perl5/perlbrew/perls/perl-5.22.0/bin/perl
  Config: -de -Dprefix=/Users/matatk/perl5/perlbrew/perls/perl-5.22.0 -Aeval:scriptdir=/Users/matatk/perl5/perlbrew/perls/perl-5.22.0/bin
  Compiled at: Dec 10 2015 23:37:57

perlbrew:
  version: 0.74
  ENV:
    PERLBREW_ROOT: /Users/matatk/perl5/perlbrew
    PERLBREW_HOME: /Users/matatk/.perlbrew
    PERLBREW_PATH: /Users/matatk/perl5/perlbrew/bin:/Users/matatk/perl5/perlbrew/perls/perl-5.22.0/bin
    PERLBREW_MANPATH: /Users/matatk/perl5/perlbrew/perls/perl-5.22.0/man
```

I found this error in the same module, but I don't think it apples here: https://gitlab.com/cpran/plugin_cpran/issues/29 -- however it made me wonder if Make is not putting the (required on NIXes) `./` before the filename when it performs the substitution in the `test` target.  The earlier version of TESTickle had `bin/blah` there so the `./` was not needed.  I'm not sure if there's a nice cross-platform way to include the `./` or not, but the [GNU Make Manual](https://www.gnu.org/software/make/manual/) is very comprehensive.

**Comment by matatk** [comment]
I’ve just realised that [line 18 of the `Makefile`](https://github.com/MarkWithall/TESTickle/blob/master/Makefile#L18) has been changed back to _not_ depend on `sample.test` anymore, so when I was running `make test` it was bound to fail unless I did a `make` first.

Anyway, as of the latest code (1465b7d81f1a54eeea8f7d9bc81b5a0f32a2e8c4)
- If I do `make && make test` then the `prove` now works.
- If I remove the `./` it will fail — so that is definitively vital.

Therefore, adding back `sample.test$(DOTEXE)` after line 18 is sufficient to make `make test` work 'out of the box'.  Sorry if I have caused any confusion over this!

I've just submitted Pull Request #8 to provide these fixes.

**Comment by matatk** [comment]
This was fixed in #8 by 2c736071976ba16d43477e10ab75dfe345168a14 :-)

**Comment by matatk** [comment]
I found what might be a better way of making sure that the full path (i.e. including current directory) of the test binaries is provided to `prove`: https://github.com/matatk/LEDstrip/blob/submodule-testickle/switched/tests/Makefile#L25

Just in case that ever breaks, here's the relevant code from the Makefile:

``` make
test: ledlib_battery.test$(DOTEXE) ledlib_dispatch.test$(DOTEXE)
    prove -f -e "" $(addprefix ./,$^)
```

What this does is prefix `./` to all of the strings (filenames) in the list (`$^` -- the list of all pre-requisites, in this case).  I've not been able to test this on Windows, but it does seem neater, as it works when there are >1 pre-requisites.

**Comment by MarkWithall** [comment]
Yes, that works fine on Windows.

**Comment by matatk** [comment]
Ah, great, thanks for testing :-).
